"""crear tablas hce cu28

Revision ID: 542a2d173d71
Revises: e9b1a6ac1592
Create Date: 2026-08-30 22:26:29.271007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542a2d173d71'
down_revision: Union[str, Sequence[str], None] = 'e9b1a6ac1592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea las tablas de soporte del CU28 (HCE) con soporte multitenant (id_clinica).

    - citas: tabla de soporte para la FK de consultas.id_cita.
    - historias_clinicas, consultas y diagnosticos con aislamiento por id_clinica.
    """
    # Tabla citas
    op.execute("""
        CREATE TABLE IF NOT EXISTS citas (
            id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_paciente BIGINT NOT NULL REFERENCES pacientes(id_paciente) ON DELETE RESTRICT,
            id_medico BIGINT NOT NULL REFERENCES medicos(id_medico) ON DELETE RESTRICT,
            id_servicio BIGINT,
            fecha_hora_inicio TIMESTAMP,
            fecha_hora_fin TIMESTAMP,
            modalidad VARCHAR(50),
            motivo TEXT,
            estado VARCHAR(30),
            check_in TIMESTAMP,
            fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Historia clinica base del paciente (scoped a id_clinica)
    op.execute("""
        CREATE TABLE IF NOT EXISTS historias_clinicas (
            id_historia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica) ON DELETE RESTRICT,
            id_paciente BIGINT NOT NULL REFERENCES pacientes(id_paciente) ON DELETE RESTRICT,
            numero_historia VARCHAR(100) NOT NULL,
            antecedentes_personales TEXT,
            antecedentes_familiares TEXT,
            alergias TEXT,
            habitos TEXT,
            observaciones TEXT,
            fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_hce_clinica_numero UNIQUE (id_clinica, numero_historia),
            CONSTRAINT uq_hce_clinica_paciente UNIQUE (id_clinica, id_paciente)
        )
    """)

    # Encuentro clinico / evolucion (scoped a id_clinica)
    op.execute("""
        CREATE TABLE IF NOT EXISTS consultas (
            id_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica) ON DELETE RESTRICT,
            id_historia BIGINT NOT NULL REFERENCES historias_clinicas(id_historia) ON DELETE RESTRICT,
            id_cita BIGINT NOT NULL REFERENCES citas(id_cita) ON DELETE RESTRICT,
            id_medico BIGINT NOT NULL REFERENCES medicos(id_medico) ON DELETE RESTRICT,
            motivo_consulta TEXT NOT NULL,
            sintomas TEXT NOT NULL,
            examen_fisico TEXT,
            signos_vitales JSONB,
            observaciones TEXT,
            evolucion TEXT NOT NULL,
            plan_medico TEXT NOT NULL,
            datos_especialidad JSONB,
            fecha_consulta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Diagnosticos CIE-10
    op.execute("""
        CREATE TABLE IF NOT EXISTS diagnosticos (
            id_diagnostico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_consulta BIGINT NOT NULL REFERENCES consultas(id_consulta) ON DELETE CASCADE,
            codigo_cie VARCHAR(30) NOT NULL,
            descripcion TEXT NOT NULL,
            tipo VARCHAR(30) NOT NULL,
            observaciones TEXT,
            fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Indices
    op.execute("CREATE INDEX IF NOT EXISTS idx_historias_clinica ON historias_clinicas(id_clinica)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_historias_paciente ON historias_clinicas(id_paciente)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_consultas_clinica ON consultas(id_clinica)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_consultas_historia ON consultas(id_historia)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_consultas_cita ON consultas(id_cita)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_consultas_medico ON consultas(id_medico)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_diagnosticos_consulta ON diagnosticos(id_consulta)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_diagnosticos_cie ON diagnosticos(codigo_cie)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS diagnosticos CASCADE")
    op.execute("DROP TABLE IF EXISTS consultas CASCADE")
    op.execute("DROP TABLE IF EXISTS historias_clinicas CASCADE")
    op.execute("DROP TABLE IF EXISTS citas CASCADE")
