"""002_alinear_ddl

Revision ID: 
Revises: 001_crear_tabla_usuarios
Create Date: 2026-08-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, func, ForeignKey

# revision identifiers, used by Alembic.
revision: str = '002_alinear_ddl'
down_revision: Union[str, None] = '001_crear_tabla_usuarios'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def tables_exist(connection, table_names):
    """Check if tables exist in the database."""
    inspector = inspect(connection)
    existing_tables = inspector.get_table_names()
    return all(t in existing_tables for t in table_names)


def columns_exist(connection, table_name, column_names):
    """Check if columns exist in a table."""
    inspector = inspect(connection)
    existing_columns = [c['name'] for c in inspector.get_columns(table_name)]
    return all(c in existing_columns for c in column_names)


def upgrade() -> None:
    bind = op.get_bind()
    
    # Crear tablas solo si no existen usando IF NOT EXISTS
    # y agregar columnas a usuarios si faltan
    
    # Agregar columnas id_clinica e id_rol a usuarios si no existen
    conn = op.get_bind()
    insp = inspect(conn)
    existing_cols = [c['name'] for c in insp.get_columns('usuarios')]
    if 'id_clinica' not in existing_cols:
        op.add_column('usuarios', sa.Column('id_clinica', sa.BigInteger(), sa.ForeignKey('clinicas.id_clinica'), nullable=True))
    if 'id_rol' not in existing_cols:
        op.add_column('usuarios', sa.Column('id_rol', sa.BigInteger(), sa.ForeignKey('roles.id_rol'), nullable=True))
    
    # Crear tablas solo si no existen (usando SQL raw con IF NOT EXISTS)
    # Clinicas
    op.execute("""
        CREATE TABLE IF NOT EXISTS clinicas (
            id_clinica BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(150) NOT NULL,
            razon_social VARCHAR(200),
            nit VARCHAR(50) UNIQUE,
            telefono VARCHAR(30),
            correo VARCHAR(150),
            direccion VARCHAR(250),
            logo VARCHAR(500),
            estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
            fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    # Roles
    op.execute("""
        CREATE TABLE IF NOT EXISTS roles (
            id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT REFERENCES clinicas(id_clinica),
            nombre VARCHAR(100) NOT NULL,
            descripcion TEXT,
            estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO')
        """)
    # Notificaciones
    op.execute("""
        CREATE TABLE IF NOT EXISTS notificaciones (
            id_notificacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario),
            tipo VARCHAR(50),
            canal VARCHAR(30),
            titulo VARCHAR(200),
            mensaje TEXT,
            fecha_programada TIMESTAMP,
            fecha_envio TIMESTAMP,
            fecha_lectura TIMESTAMP,
            estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE')
        """)
    # Auditoría
    op.execute("""
        CREATE TABLE IF NOT EXISTS auditoria (
            id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario),
            tabla_afectada VARCHAR(150),
            registro_id BIGINT,
            accion VARCHAR(50) NOT NULL,
            descripcion TEXT,
            datos_anteriores JSONB,
            datos_nuevos JSONB,
            direccion_ip VARCHAR(45),
            fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
        """)
    
    # Ahora agregar las restricciones y índices que faltan
    # Agregar restricción única en nit de clinicas si no existe
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'clinicas_nit_key') THEN
                CREATE UNIQUE INDEX IF NOT EXISTS clinitas_nit_key ON clinicas (nit);
            END IF;
        END$$;
    """)
    
    # Agregar restricción única en numero_historia de historias_clinicas si la tabla existe
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'historias_clinicas') THEN
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'historias_clinicas_numero_historia_key') THEN
                    CREATE UNIQUE INDEX historias_clinicas_numero_historia_key ON historias_clinicas (numero_historia);
                END IF;
            END IF;
        END$$;
    """)
    

def downgrade() -> None:
    # Lógica reversa: eliminar las columnas agregadas y dropar tablas
    conn = op.get_bind()
    insp = inspect(conn)
    # Verificar si las columnas existen antes de eliminarlas
    existing_cols = [c['name'] for c in insp.get_columns('usuarios')]
    if 'id_clinica' in existing_cols:
        op.drop_column('usuarios', 'id_clinica')
    if 'id_rol' in existing_cols:
        op.drop_column('usuarios', 'id_rol')
    
    # Dropar tablas solo si existen
    op.execute("DROP TABLE IF EXISTS auditoria")
    op.execute("DROP TABLE IF EXISTS notificaciones")
    op.execute("DROP TABLE IF EXISTS roles")
    op.execute("DROP TABLE IF EXISTS clinicas")
    
    # Restablecer restricciones únicas
    op.execute("""
        DROP INDEX IF EXISTS clinitas_nit_key;
        DROP INDEX IF EXISTS historias_clinicas_numero_historia_key;
    """)