"""003_crear_permisos

Crea las tablas faltantes del módulo de Roles y Permisos (CU26):
- `permisos` (catálogo de permisos, modelado por app.modules.auth.models.Permiso)
- `rol_permisos` (asignación N:M rol <-> permiso, modelada por RolPermiso)

Además agrega la columna `fecha_creacion` a `roles` para alinear la tabla
con el modelo ORM Rol (la migración 002_alinear_ddl la omitió).

Revision ID: 003_crear_permisos
Revises: e9b1a6ac1592
Create Date: 2026-09-06 00:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '003_crear_permisos'
down_revision: Union[str, Sequence[str], None] = 'e9b1a6ac1592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # 1. Agregar fecha_creacion a roles si no existe (el modelo Rol la mapea)
    if 'roles' in inspect(conn).get_table_names():
        existing_cols = [c['name'] for c in inspect(conn).get_columns('roles')]
        if 'fecha_creacion' not in existing_cols:
            op.add_column(
                'roles',
                sa.Column(
                    'fecha_creacion',
                    sa.DateTime(timezone=True),
                    server_default=sa.text('now()'),
                    nullable=False,
                ),
            )

    # 2. Catálogo de permisos (CU26)
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS permisos (
            id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            descripcion TEXT,
            modulo VARCHAR(100) NOT NULL,
            accion VARCHAR(100) NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ix_permisos_modulo_accion
        ON permisos (modulo, accion)
        """
    )

    # 3. Asignación N:M rol <-> permiso (CU26)
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS rol_permisos (
            id_rol BIGINT NOT NULL REFERENCES roles(id_rol) ON DELETE CASCADE,
            id_permiso BIGINT NOT NULL REFERENCES permisos(id_permiso) ON DELETE CASCADE,
            PRIMARY KEY (id_rol, id_permiso)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS rol_permisos")
    op.execute("DROP TABLE IF EXISTS permisos")
    op.execute("ALTER TABLE roles DROP COLUMN IF EXISTS fecha_creacion")