"""crear_tabla_citas

Revision ID: 003_crear_tabla_citas
Revises: 002b_crear_tablas_base
Create Date: 2026-08-25 12:00:00.000000

Nota: esta migracion se reproduce de forma idempotente (CREATE TABLE IF NOT
EXISTS). Antes declaraba ``down_revision = 'e9b1a6ac1592'``, una revision que
existe en la base de datos de Neon pero nunca estuvo en el repositorio, lo que
rompia la cadena (``alembic history`` fallaba con KeyError). Ahora encadena
desde 002b_crear_tablas_base, que crea las tablas ``pacientes``, ``medicos`` y
``especialidades`` que esta migracion referencia.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_crear_tabla_citas'
down_revision: Union[str, Sequence[str], None] = '002b_crear_tablas_base'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la tabla citas si no existe (idempotente)."""
    op.execute("""
        CREATE TABLE IF NOT EXISTS citas (
            id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_paciente BIGINT NOT NULL REFERENCES pacientes(id_paciente),
            id_medico BIGINT NOT NULL REFERENCES medicos(id_medico),
            id_especialidad BIGINT REFERENCES especialidades(id_especialidad),
            fecha_cita DATE NOT NULL,
            hora_inicio VARCHAR(10) NOT NULL,
            hora_fin VARCHAR(10),
            motivo TEXT,
            estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
            tipo_consulta VARCHAR(30) NOT NULL DEFAULT 'TELECONSULTA',
            notas TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)


def downgrade() -> None:
    """Elimina la tabla citas (solo si no contiene datos)."""
    op.execute("DROP TABLE IF EXISTS citas")