"""crear tablas agenda cu05

Revision ID: b1c2d3e4f5a6
Revises: 542a2d173d71
Create Date: 2026-09-10 02:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, Sequence[str], None] = '542a2d173d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea las tablas del CU05 (Agenda Médica):
    - servicios_medicos: catálogo global de servicios/prestaciones médicas.
    - horarios_medicos: configuración de días laborables y horarios por médico.
    - bloqueos_agenda: solicitudes y aprobaciones de bloqueo de turnos.
    """
    # 1. Tabla servicios_medicos
    op.execute("""
        CREATE TABLE IF NOT EXISTS servicios_medicos (
            id_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            descripcion TEXT,
            hora_inicio TIME NOT NULL,
            hora_fin TIME NOT NULL,
            duracion_minutos INTEGER NOT NULL,
            costo NUMERIC(10, 2) NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'activo'
        )
    """)

    # 2. Tabla horarios_medicos
    op.execute("""
        CREATE TABLE IF NOT EXISTS horarios_medicos (
            id_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_medico BIGINT NOT NULL REFERENCES medicos(id_medico) ON DELETE CASCADE,
            id_servicio BIGINT NOT NULL REFERENCES servicios_medicos(id_servicio) ON DELETE CASCADE,
            dia_semana INTEGER NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'activo',
            CONSTRAINT uq_horarios_medico_servicio_dia UNIQUE (id_medico, id_servicio, dia_semana)
        )
    """)

    # 3. Tabla bloqueos_agenda
    op.execute("""
        CREATE TABLE IF NOT EXISTS bloqueos_agenda (
            id_bloqueo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_medico BIGINT NOT NULL REFERENCES medicos(id_medico) ON DELETE CASCADE,
            id_servicio BIGINT NOT NULL REFERENCES servicios_medicos(id_servicio) ON DELETE CASCADE,
            fecha DATE NOT NULL,
            hora_inicio TIME NOT NULL,
            hora_fin TIME NOT NULL,
            motivo TEXT NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        )
    """)

    # Indices
    op.execute("CREATE INDEX IF NOT EXISTS idx_horarios_medicos_medico ON horarios_medicos(id_medico)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_horarios_medicos_servicio ON horarios_medicos(id_servicio)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_bloqueos_agenda_medico ON bloqueos_agenda(id_medico)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_bloqueos_agenda_servicio ON bloqueos_agenda(id_servicio)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_bloqueos_agenda_fecha ON bloqueos_agenda(fecha)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS bloqueos_agenda CASCADE")
    op.execute("DROP TABLE IF EXISTS horarios_medicos CASCADE")
    op.execute("DROP TABLE IF EXISTS servicios_medicos CASCADE")
