"""crear_documentos_clinicos

Revision ID: 004_crear_documentos_clinicos
Revises: 003_crear_tabla_citas
Create Date: 2026-09-06 00:00:00.000000

CU12 - Consultar Documentos Clínicos y Exámenes.
Crea las tablas permisos, rol_permisos y documentos_clinicos (idempotente),
siembra los roles base del sistema (si no existen), los permisos granulares
documents:* y su asignación por rol conforme a la matriz CU12. Además agrega
la columna id_clinica a pacientes (el modelo ORM la declara pero Neon no la
tiene; sin ella falla toda consulta al modelo Paciente).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_crear_documentos_clinicos'
down_revision: Union[str, Sequence[str], None] = '003_crear_tabla_citas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISOS_CU12 = [
    ("documents:read:prescriptions", "Leer recetas médicas", "medical_records", "read_prescriptions"),
    ("documents:read:lab_orders", "Leer órdenes de laboratorio", "medical_records", "read_lab_orders"),
    ("documents:read:lab_results", "Leer resultados de laboratorio", "medical_records", "read_lab_results"),
    ("documents:read:certificates", "Leer certificados e indicaciones médicas", "medical_records", "read_certificates"),
    ("documents:download", "Descargar documentos clínicos", "medical_records", "download"),
    ("documents:search", "Buscar y listar documentos clínicos", "medical_records", "search"),
]

# Matriz CU12: rol -> nombres de permiso asignados
MATRIZ_ROLES_PERMISOS = {
    "ADMIN": [p[0] for p in PERMISOS_CU12],
    "MEDICO": [p[0] for p in PERMISOS_CU12],
    "RECEPCION": [p[0] for p in PERMISOS_CU12 if p[0] != "documents:read:lab_results"],
    "PACIENTE": [p[0] for p in PERMISOS_CU12],
}


def upgrade() -> None:
    bind = op.get_bind()

    # ------------------------------------------------------------------ #
    # 1. permisos y rol_permisos (RBAC granular)
    # ------------------------------------------------------------------ #
    op.execute("""
        CREATE TABLE IF NOT EXISTS permisos (
            id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            descripcion TEXT,
            modulo VARCHAR(100) NOT NULL,
            accion VARCHAR(100) NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS rol_permisos (
            id_rol BIGINT NOT NULL REFERENCES roles(id_rol) ON DELETE CASCADE,
            id_permiso BIGINT NOT NULL REFERENCES permisos(id_permiso) ON DELETE CASCADE,
            PRIMARY KEY (id_rol, id_permiso)
        )
    """)

    # ------------------------------------------------------------------ #
    # 2. documentos_clinicos (CU12)
    # ------------------------------------------------------------------ #
    op.execute("""
        CREATE TABLE IF NOT EXISTS documentos_clinicos (
            id_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            id_paciente BIGINT REFERENCES pacientes(id_paciente),
            id_cita BIGINT REFERENCES citas(id_cita),
            tipo_documento VARCHAR(30) NOT NULL
                CHECK (tipo_documento IN ('RECETA', 'ORDEN_LAB', 'RESULTADO_LAB', 'CERTIFICADO', 'INDICACION')),
            titulo VARCHAR(200) NOT NULL,
            descripcion TEXT,
            archivo_url VARCHAR(500) NOT NULL,
            hash_archivo VARCHAR(64) NOT NULL,
            firmado_por BIGINT REFERENCES usuarios(id_usuario),
            fecha_documento DATE NOT NULL,
            metadatos JSONB,
            estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO'
                CHECK (estado IN ('ACTIVO', 'ANULADO')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_docs_clinica_paciente ON documentos_clinicos (id_clinica, id_paciente)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_docs_clinica_tipo ON documentos_clinicos (id_clinica, tipo_documento)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_docs_clinica_fecha ON documentos_clinicos (id_clinica, fecha_documento)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_docs_clinica_titulo ON documentos_clinicos (id_clinica, titulo)
    """)

    # ------------------------------------------------------------------ #
    # 3. Agregar columna id_clinica a pacientes (alinear modelo ORM)
    # ------------------------------------------------------------------ #
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'pacientes'
                  AND column_name = 'id_clinica'
            ) THEN
                ALTER TABLE pacientes ADD COLUMN id_clinica BIGINT REFERENCES clinicas(id_clinica);
                CREATE INDEX IF NOT EXISTS ix_pacientes_id_clinica ON pacientes (id_clinica);
            END IF;
        END$$
    """)

    # ------------------------------------------------------------------ #
    # 4. Seed de roles base del sistema (si no existen)
    # ------------------------------------------------------------------ #
    roles = [
        ("ADMIN", "Administrador del sistema / clínica"),
        ("MEDICO", "Médico / especialista"),
        ("RECEPCION", "Personal de recepción"),
        ("PACIENTE", "Paciente"),
    ]
    for nombre, desc in roles:
        op.execute(
            sa.text(
                "INSERT INTO roles (nombre, descripcion, estado) "
                "SELECT :n, :d, 'ACTIVO' "
                "WHERE NOT EXISTS (SELECT 1 FROM roles WHERE UPPER(nombre) = UPPER(:nq))"
            ).bindparams(n=nombre, d=desc, nq=nombre)
        )

    # ------------------------------------------------------------------ #
    # 5. Seed de permisos documents:* (si no existen)
    # ------------------------------------------------------------------ #
    for nombre, desc, modulo, accion in PERMISOS_CU12:
        op.execute(
            sa.text(
                "INSERT INTO permisos (nombre, descripcion, modulo, accion, estado) "
                "SELECT :n, :d, :m, :a, 'ACTIVO' "
                "WHERE NOT EXISTS (SELECT 1 FROM permisos WHERE nombre = :nq)"
            ).bindparams(n=nombre, d=desc, m=modulo, a=accion, nq=nombre)
        )

    # ------------------------------------------------------------------ #
    # 6. Asignación prendida rol_permisos conforme a la matriz CU12
    # ------------------------------------------------------------------ #
    for rol_name, permisos in MATRIZ_ROLES_PERMISOS.items():
        for perm_nombre in permisos:
            op.execute(
                sa.text(
                    "INSERT INTO rol_permisos (id_rol, id_permiso) "
                    "SELECT r.id_rol, p.id_permiso "
                    "FROM roles r, permisos p "
                    "WHERE UPPER(r.nombre) = UPPER(:rn) AND p.nombre = :pn "
                    "AND NOT EXISTS ("
                    "  SELECT 1 FROM rol_permisos rp "
                    "  WHERE rp.id_rol = r.id_rol AND rp.id_permiso = p.id_permiso"
                    ")"
                ).bindparams(rn=rol_name, pn=perm_nombre)
            )


def downgrade() -> None:
    """Revierte los cambios del CU12 (solo si no hay datos que preservar)."""
    op.execute("DROP INDEX IF EXISTS idx_docs_clinica_titulo")
    op.execute("DROP INDEX IF EXISTS idx_docs_clinica_fecha")
    op.execute("DROP INDEX IF EXISTS idx_docs_clinica_tipo")
    op.execute("DROP INDEX IF EXISTS idx_docs_clinica_paciente")
    op.execute("DROP TABLE IF EXISTS documentos_clinicos")
    op.execute("DROP TABLE IF EXISTS rol_permisos")
    op.execute("DROP TABLE IF EXISTS permisos")

    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'pacientes'
                  AND column_name = 'id_clinica'
            ) THEN
                ALTER TABLE pacientes DROP COLUMN IF EXISTS id_clinica;
            END IF;
        END$$
    """)