"""crear_tabla_sesiones_activas

Revision ID: 005_crear_tabla_sesiones_activas
Revises: 004_crear_documentos_clinicos
Create Date: 2026-10-02 00:00:00.000000

CU23 - Recuperar Contraseña y Aplicar Cierre Automático.

Crea `sesiones_activas` para medir la inactividad POR SESIÓN y no por usuario,
que es lo que permite cerrar solo el dispositivo inactivo y dejar vivas las
demas sesiones del mismo usuario (decision D1 del change
`cu23-recuperacion-contrasena-cierre-automatico`).

Nota importante sobre `token_blacklist` y `usuarios.token_version`: ambas cosas
YA EXISTEN en el esquema desplegado de Neon, pero sin revision en este
repositorio. Se formalizan aqui de forma IDEMPOTENTE (`IF NOT EXISTS`) para que
una base creada desde cero por las migraciones quede igual que la desplegada; en
Neon son no-ops.

En `token_blacklist` se reutiliza la estructura tal cual (decision D2): la
columna `token` almacena el `jti`, que es un UUID hexadecimal y encaja en el
VARCHAR existente. La columna de fecha se llama `revoked_at` en el esquema real,
y el modelo la mapea explicitamente a ese nombre.

`token_version` es required por el contrato de autenticacion para el cierre
global de sesion de CU24, asi que la columna debe existir tambien en una base
nueva, no solo en la desplegada.

El `downgrade` NO borra `token_blacklist` ni `token_version`: son objetos que ya
existian en el esquema desplegado y eliminarlos destruiria datos que esta
revision no creo. Solo se revierte lo que si es exclusivo de esta revision.

Se usa SQL crudo e idempotente, igual que 002, 003 y 004, porque Alembic no
resuelve la FK referenciada al renderizar esta tabla en modo offline.
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '005_crear_tabla_sesiones_activas'
down_revision: Union[str, Sequence[str], None] = '004_crear_documentos_clinicos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `usuarios.token_version` ya existe en Neon; en una base nueva hay que
    # crearla para que el modelo y el contrato de auth funcionen.
    op.execute("""
        ALTER TABLE usuarios
        ADD COLUMN IF NOT EXISTS token_version BIGINT NOT NULL DEFAULT 0
    """)

    # Formaliza la tabla preexistente de Neon. IF NOT EXISTS la deja intacta si
    # ya existe, de modo que aplicar esto en la base desplegada no la altera.
    op.execute("""
        CREATE TABLE IF NOT EXISTS token_blacklist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            token VARCHAR(500) NOT NULL,
            revoked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_token_blacklist_token
        ON token_blacklist (token)
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS sesiones_activas (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            jti VARCHAR(64) NOT NULL,
            id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario),
            id_clinica BIGINT,
            creada_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            ultima_actividad TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            revocada_en TIMESTAMPTZ
        )
    """)
    # Indice unico: es la via de busqueda de cada peticion autenticada, asi que
    # un jti duplicado debe ser imposible, no solo improbable.
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS ix_sesiones_activas_jti
        ON sesiones_activas (jti)
    """)
    # Permite purgar sesiones revocadas antigamente y listar por usuario.
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_sesiones_activas_usuario
        ON sesiones_activas (id_usuario)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS sesiones_activas")
    # `token_blacklist` y `usuarios.token_version` se dejan intactos a proposito:
    # ya existian en el esquema desplegado antes de esta revision, asi que
    # borrarlos destruiria datos ajenos a CU23.
