"""crear_ordenes_laboratorio

Revision ID: 006_crear_ordenes_laboratorio
Revises: 005_crear_tabla_sesiones_activas
Create Date: 2026-10-03 00:00:00.000000

CU10 - Emitir Solicitudes de Exámenes de Laboratorio.

Crea tabla `ordenes_laboratorio` para órdenes firmadas digitalmente
e integradas en HCE (documentos_clinicos tipo ORDEN_LAB).
"""
from typing import Sequence, Union
from alembic import op

revision: str = '006_crear_ordenes_laboratorio'
down_revision: Union[str, Sequence[str], None] = '005_crear_tabla_sesiones_activas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS ordenes_laboratorio (
            id_orden BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            id_paciente BIGINT NOT NULL,
            id_cita BIGINT,
            id_medico BIGINT NOT NULL REFERENCES usuarios(id_usuario),
            examenes JSONB NOT NULL,
            firma_digital VARCHAR(64),
            fecha_orden DATE NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR'
                CHECK (estado IN ('BORRADOR', 'FIRMADA', 'ANULADA')),
            archivo_url VARCHAR(500),
            hash_archivo VARCHAR(64),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ordenes_clinica_paciente
        ON ordenes_laboratorio (id_clinica, id_paciente)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ordenes_clinica_medico
        ON ordenes_laboratorio (id_clinica, id_medico)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ordenes_clinica_estado
        ON ordenes_laboratorio (id_clinica, estado)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_ordenes_clinica_fecha
        ON ordenes_laboratorio (id_clinica, fecha_orden)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS ordenes_laboratorio")