"""crear_catalogo_examenes

Revision ID: 007_crear_catalogo_examenes
Revises: 006_crear_ordenes_laboratorio
Create Date: 2026-10-03 00:00:00.000000

CU10 - Catálogo de exámenes de laboratorio por clínica.
"""
from typing import Sequence, Union
from alembic import op

revision: str = '007_crear_catalogo_examenes'
down_revision: Union[str, Sequence[str], None] = '006_crear_ordenes_laboratorio'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS examenes_laboratorio (
            id_examen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            codigo VARCHAR(50) NOT NULL,
            nombre VARCHAR(200) NOT NULL,
            categoria VARCHAR(50) NOT NULL,
            precio_referencia BIGINT,
            activo VARCHAR(10) NOT NULL DEFAULT 'SI' CHECK (activo IN ('SI', 'NO')),
            requiere_ayuno BIGINT NOT NULL DEFAULT 0,
            tiempo_entrega_horas BIGINT NOT NULL DEFAULT 24,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_examenes_clinica_codigo
        ON examenes_laboratorio (id_clinica, codigo)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_examenes_clinica_activo
        ON examenes_laboratorio (id_clinica, activo)
    """)

    # Seed mínimo de exámenes comunes (idempotente con ON CONFLICT DO NOTHING).
    # NOTA FIX FK: la versión anterior hacía INSERT con id_clinica=1 hardcodeado,
    # lo que rompía en BDs nuevas donde `clinicas` está vacía:
    #   ForeignKeyViolation: La llave (id_clinica)=(1) no está presente en «clinicas».
    # Se cambia a INSERT ... SELECT desde `clinicas`: siembra el catálogo para
    # TODAS las clínicas existentes y no inserta nada (en vez de fallar) si aún
    # no hay clínicas. No inventa tenants falsos.
    op.execute("""
        INSERT INTO examenes_laboratorio (id_clinica, codigo, nombre, categoria, precio_referencia, activo, requiere_ayuno, tiempo_entrega_horas)
        SELECT c.id_clinica, v.codigo, v.nombre, v.categoria, v.precio_referencia, v.activo, v.requiere_ayuno, v.tiempo_entrega_horas
        FROM clinicas c
        CROSS JOIN (VALUES
            ('HEMOGRAMA', 'Hemograma Completo', 'HEMATOLOGIA', 15000, 'SI', 0, 4),
            ('GLUCOSA', 'Glucosa en Sangre', 'BIOQUIMICA', 8000, 'SI', 1, 2),
            ('CREATININA', 'Creatinina Sérica', 'BIOQUIMICA', 8000, 'SI', 0, 4),
            ('UREA', 'Urea Sérica', 'BIOQUIMICA', 8000, 'SI', 0, 4),
            ('COLESTEROL_TOTAL', 'Colesterol Total', 'BIOQUIMICA', 12000, 'SI', 1, 4),
            ('TRIGLICERIDOS', 'Triglicéridos', 'BIOQUIMICA', 12000, 'SI', 1, 4),
            ('HEMOGLOBINA_GLICADA', 'Hemoglobina Glicada (HbA1c)', 'BIOQUIMICA', 25000, 'SI', 0, 24),
            ('TGO_TGP', 'Transaminasas (TGO/TGP)', 'BIOQUIMICA', 15000, 'SI', 0, 4),
            ('ORINA_COMPLETA', 'Orina Completa', 'OTROS', 10000, 'SI', 0, 4),
            ('COPROLOGICO', 'Coprológico Serie', 'MICROBIOLOGIA', 18000, 'SI', 0, 24)
        ) AS v(codigo, nombre, categoria, precio_referencia, activo, requiere_ayuno, tiempo_entrega_horas)
        ON CONFLICT (id_clinica, codigo) DO NOTHING
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS examenes_laboratorio")