"""008_tablas_recetas_cu16

Revision ID: a8b9c0d1e2f3
Revises: f6a7b8c9d0e1
Create Date: 2026-09-23 00:00:00.000000

Crea las tablas del CU16 (Recetas Médicas Digitales):
medicamentos, recetas, receta_detalle, configuracion_recetas,
secuencias_recetas, receta_idempotencia y receta_validacion_intentos,
y siembra los permisos RBAC prescriptions:*.

Ver specs/openspec/changes/cu16-recetas-digitales/design.md
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b9c0d1e2f3'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISOS_CU16 = [
    ("prescriptions:issue", "Emitir recetas médicas digitales", "prescriptions", "issue"),
    ("prescriptions:read", "Listar y consultar recetas médicas", "prescriptions", "read"),
    ("prescriptions:download", "Descargar PDF de recetas médicas", "prescriptions", "download"),
    ("prescriptions:cancel", "Anular recetas médicas", "prescriptions", "cancel"),
    ("prescriptions:catalog:write", "Administrar catálogo global de medicamentos", "prescriptions", "catalog_write"),
]

MATRIZ_ROLES_PERMISOS_CU16 = {
    "ADMIN": [p[0] for p in PERMISOS_CU16],
    "MEDICO": ["prescriptions:issue", "prescriptions:read", "prescriptions:download"],
    "PACIENTE": ["prescriptions:read", "prescriptions:download"],
}


def upgrade() -> None:
    # 1. Catálogo global de medicamentos (sin id_clinica por diseño)
    op.execute("""
        CREATE TABLE IF NOT EXISTS medicamentos (
            id_medicamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(200) NOT NULL,
            principio_activo VARCHAR(200),
            concentracion VARCHAR(100),
            forma_farmaceutica VARCHAR(100),
            descripcion TEXT,
            estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ck_medicamentos_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_medicamentos_normalizado
        ON medicamentos (
            LOWER(nombre),
            COALESCE(LOWER(concentracion), ''),
            COALESCE(LOWER(forma_farmaceutica), '')
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_medicamentos_nombre ON medicamentos (nombre)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_medicamentos_estado ON medicamentos (estado)")

    # 2. Recetas (documento clínico legal e inmutable)
    op.execute("""
        CREATE TABLE IF NOT EXISTS recetas (
            id_receta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            id_consulta BIGINT NOT NULL REFERENCES consultas(id_consulta),
            id_medico BIGINT NOT NULL REFERENCES medicos(id_medico),
            id_paciente BIGINT NOT NULL REFERENCES pacientes(id_paciente),
            id_documento BIGINT UNIQUE REFERENCES documentos_clinicos(id_documento),
            id_receta_sustituta BIGINT REFERENCES recetas(id_receta),
            folio VARCHAR(40) NOT NULL,
            codigo_verificacion_hash CHAR(64) NOT NULL UNIQUE,
            indicaciones_generales TEXT,
            firma_digital TEXT NOT NULL,
            algoritmo_firma VARCHAR(20) NOT NULL DEFAULT 'ED25519',
            key_id VARCHAR(100) NOT NULL,
            version_payload SMALLINT NOT NULL DEFAULT 1,
            hash_pdf CHAR(64) NOT NULL,
            fecha_emision TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            fecha_vencimiento DATE NOT NULL,
            estado VARCHAR(20) NOT NULL DEFAULT 'EMITIDA',
            motivo_anulacion TEXT,
            observaciones_anulacion TEXT,
            fecha_anulacion TIMESTAMPTZ,
            anulado_por BIGINT REFERENCES usuarios(id_usuario),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_recetas_clinica_folio UNIQUE (id_clinica, folio),
            CONSTRAINT ck_recetas_estado CHECK (estado IN ('EMITIDA', 'ANULADA')),
            CONSTRAINT ck_recetas_algoritmo CHECK (algoritmo_firma = 'ED25519')
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_recetas_clinica_paciente ON recetas (id_clinica, id_paciente)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_recetas_clinica_medico ON recetas (id_clinica, id_medico)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_recetas_clinica_estado ON recetas (id_clinica, estado)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_recetas_clinica_emision ON recetas (id_clinica, fecha_emision)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_recetas_consulta ON recetas (id_consulta)")

    # 3. Detalle con XOR catálogo/manual y snapshots inmutables
    op.execute("""
        CREATE TABLE IF NOT EXISTS receta_detalle (
            id_receta_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_receta BIGINT NOT NULL REFERENCES recetas(id_receta) ON DELETE CASCADE,
            id_medicamento BIGINT REFERENCES medicamentos(id_medicamento) ON DELETE RESTRICT,
            nombre_medicamento_manual VARCHAR(200),
            medicamento_nombre VARCHAR(200) NOT NULL,
            principio_activo VARCHAR(200),
            concentracion VARCHAR(100),
            forma_farmaceutica VARCHAR(100),
            dosis VARCHAR(100) NOT NULL,
            frecuencia VARCHAR(100) NOT NULL,
            duracion VARCHAR(100) NOT NULL,
            via_administracion VARCHAR(30) NOT NULL,
            cantidad INTEGER NOT NULL,
            indicaciones TEXT,
            posicion INTEGER NOT NULL DEFAULT 1,
            CONSTRAINT ck_receta_detalle_via CHECK (via_administracion IN (
                'ORAL', 'SUBLINGUAL', 'INTRAMUSCULAR', 'INTRAVENOSA',
                'TOPICA', 'OFTALMICA', 'INHALATORIA', 'RECTAL', 'OTRA')),
            CONSTRAINT ck_receta_detalle_cantidad CHECK (cantidad > 0),
            CONSTRAINT ck_receta_detalle_medicamento_xor CHECK (
                (id_medicamento IS NOT NULL AND nombre_medicamento_manual IS NULL)
                OR (id_medicamento IS NULL AND nombre_medicamento_manual IS NOT NULL
                    AND nombre_medicamento_manual <> '')
            )
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_receta_detalle_receta ON receta_detalle (id_receta, posicion)")

    # 4. Vigencia máxima por clínica (ausencia de fila equivale a 90 días)
    op.execute("""
        CREATE TABLE IF NOT EXISTS configuracion_recetas (
            id_clinica BIGINT PRIMARY KEY REFERENCES clinicas(id_clinica),
            vigencia_maxima_dias SMALLINT NOT NULL DEFAULT 90,
            CONSTRAINT ck_config_recetas_vigencia CHECK (vigencia_maxima_dias BETWEEN 1 AND 90)
        )
    """)

    # 5. Contador atómico de folios por clínica/año
    op.execute("""
        CREATE TABLE IF NOT EXISTS secuencias_recetas (
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            anio INTEGER NOT NULL,
            ultimo_numero INTEGER NOT NULL DEFAULT 0,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id_clinica, anio)
        )
    """)

    # 6. Idempotencia de emisión (24 h; nunca guarda la clave en claro)
    op.execute("""
        CREATE TABLE IF NOT EXISTS receta_idempotencia (
            id_receta_idempotencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica),
            id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario),
            clave_hash CHAR(64) NOT NULL,
            request_hash TEXT NOT NULL,
            id_receta BIGINT REFERENCES recetas(id_receta) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT uq_receta_idempotencia_clave UNIQUE (id_clinica, id_usuario, clave_hash)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_receta_idempotencia_expira ON receta_idempotencia (expires_at)")

    # 7. Telemetría anonimizada y rate limiting de validación pública (retención 30 días)
    op.execute("""
        CREATE TABLE IF NOT EXISTS receta_validacion_intentos (
            id_validacion_intento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            codigo_hash CHAR(64) NOT NULL,
            ip_hash CHAR(64) NOT NULL,
            resultado VARCHAR(30) NOT NULL,
            fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_validacion_codigo_ventana
        ON receta_validacion_intentos (codigo_hash, fecha_hora)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_validacion_ip_ventana
        ON receta_validacion_intentos (ip_hash, fecha_hora)
    """)

    # 8. Seed permisos prescriptions:* (idempotente)
    for nombre, desc, modulo, accion in PERMISOS_CU16:
        op.execute(
            sa.text(
                "INSERT INTO permisos (nombre, descripcion, modulo, accion, estado) "
                "SELECT :n, :d, :m, :a, 'ACTIVO' "
                "WHERE NOT EXISTS (SELECT 1 FROM permisos WHERE nombre = :nq)"
            ).bindparams(n=nombre, d=desc, m=modulo, a=accion, nq=nombre)
        )

    for rol_name, permisos in MATRIZ_ROLES_PERMISOS_CU16.items():
        for perm_nombre in permisos:
            op.execute(
                sa.text(
                    "INSERT INTO rol_permisos (id_rol, id_permiso) "
                    "SELECT r.id_rol, p.id_permiso "
                    "FROM roles r, permisos p "
                    "WHERE UPPER(r.nombre) = UPPER(:rn) AND p.nombre = :pn "
                    "AND NOT EXISTS ("
                    "  SELECT 1 FROM rol_permisos rp "
                    "  WHERE rp.id_rol = r.id_rol AND rp.id_permiso = p.id_permiso"
                    ")"
                ).bindparams(rn=rol_name, pn=perm_nombre)
            )


def downgrade() -> None:
    # Revocar asignaciones y permisos sembrados por CU16
    op.execute(
        "DELETE FROM rol_permisos WHERE id_permiso IN "
        "(SELECT id_permiso FROM permisos WHERE nombre LIKE 'prescriptions:%')"
    )
    op.execute("DELETE FROM permisos WHERE nombre LIKE 'prescriptions:%'")

    op.execute("DROP INDEX IF EXISTS ix_validacion_ip_ventana")
    op.execute("DROP INDEX IF EXISTS ix_validacion_codigo_ventana")
    op.execute("DROP TABLE IF EXISTS receta_validacion_intentos")
    op.execute("DROP INDEX IF EXISTS ix_receta_idempotencia_expira")
    op.execute("DROP TABLE IF EXISTS receta_idempotencia")
    op.execute("DROP TABLE IF EXISTS secuencias_recetas")
    op.execute("DROP TABLE IF EXISTS configuracion_recetas")
    op.execute("DROP INDEX IF EXISTS ix_receta_detalle_receta")
    op.execute("DROP TABLE IF EXISTS receta_detalle")
    op.execute("DROP INDEX IF EXISTS ix_recetas_consulta")
    op.execute("DROP INDEX IF EXISTS ix_recetas_clinica_emision")
    op.execute("DROP INDEX IF EXISTS ix_recetas_clinica_estado")
    op.execute("DROP INDEX IF EXISTS ix_recetas_clinica_medico")
    op.execute("DROP INDEX IF EXISTS ix_recetas_clinica_paciente")
    op.execute("DROP TABLE IF EXISTS recetas")
    op.execute("DROP INDEX IF EXISTS ix_medicamentos_estado")
    op.execute("DROP INDEX IF EXISTS ix_medicamentos_nombre")
    op.execute("DROP INDEX IF EXISTS uq_medicamentos_normalizado")
    op.execute("DROP TABLE IF EXISTS medicamentos")
