"""Repara deriva modelo-vs-BD: roles.fecha_creacion, adjuntos de chat y token_blacklist.

Revision ID: e3f4a5b6c7d8
Revises: d2e3f4a5b6c7
"""
from alembic import op

revision = "e3f4a5b6c7d8"
down_revision = "d2e3f4a5b6c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # roles.fecha_creacion: el modelo la exige NOT NULL; la DDL original
    # (002_alinear_ddl) nunca la creó. DEFAULT cubre las filas existentes.
    op.execute(
        "ALTER TABLE roles "
        "ADD COLUMN IF NOT EXISTS fecha_creacion "
        "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP"
    )
    # Adjuntos del chat de teleconsulta CU15 (todos nulables).
    op.execute(
        "ALTER TABLE mensajes_chat_cita "
        "ADD COLUMN IF NOT EXISTS adjunto_nombre VARCHAR(255)"
    )
    op.execute(
        "ALTER TABLE mensajes_chat_cita "
        "ADD COLUMN IF NOT EXISTS adjunto_tamano VARCHAR(50)"
    )
    op.execute(
        "ALTER TABLE mensajes_chat_cita ADD COLUMN IF NOT EXISTS adjunto_url TEXT"
    )
    # Tabla de tokens revocados (logout). Nunca se portó de Sprint 1.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS token_blacklist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            token VARCHAR(500) NOT NULL UNIQUE,
            revoked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE mensajes_chat_cita DROP COLUMN IF EXISTS adjunto_url")
    op.execute("ALTER TABLE mensajes_chat_cita DROP COLUMN IF EXISTS adjunto_tamano")
    op.execute("ALTER TABLE mensajes_chat_cita DROP COLUMN IF EXISTS adjunto_nombre")
    op.execute("ALTER TABLE roles DROP COLUMN IF EXISTS fecha_creacion")
    op.execute("DROP TABLE IF EXISTS token_blacklist")
