"""Repara deriva auditoria String-vs-JSONB (modelo vs BD real).

Revision ID: f7a8b9c0d1e2
Revises: 11411f333d08
"""
from alembic import op

revision = "f7a8b9c0d1e2"
down_revision = "11411f333d08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # La BD desplegada tiene auditoria.datos_* como JSONB (002_alinear_ddl),
    # pero f6a7b8c9d0e1 los creaba como VARCHAR y el modelo ORM era String.
    # El modelo canonico ahora es JSONB().with_variant(JSON(), "sqlite")
    # (igual que fichas/hce/documentos). Si la columna aun no es JSONB,
    # se convierte con USING sin romper filas existentes. Sin bloques DO:
    # el chequeo de tipo se hace en Python y el ALTER es SQL plano.
    from sqlalchemy import inspect as sa_inspect

    conn = op.get_bind()
    try:
        cols = {c["name"]: str(c["type"]) for c in sa_inspect(conn).get_columns("auditoria")}
    except Exception:
        cols = {}

    if not cols:
        op.execute(
            "CREATE TABLE IF NOT EXISTS auditoria ("
            "id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "id_clinica BIGINT NOT NULL REFERENCES clinicas(id_clinica), "
            "id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario), "
            "tabla_afectada VARCHAR(150), registro_id BIGINT, "
            "accion VARCHAR(50) NOT NULL, descripcion TEXT, "
            "datos_anteriores JSONB, datos_nuevos JSONB, "
            "direccion_ip VARCHAR(45), "
            "fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        )
        return

    for col in ("datos_anteriores", "datos_nuevos"):
        if cols.get(col) == "JSONB":
            continue
        op.execute(
            "ALTER TABLE auditoria ALTER COLUMN " + col
            + " TYPE JSONB USING (CASE WHEN " + col + " IS NULL THEN NULL"
            + " WHEN " + col + " = '' THEN '{}'::jsonb"
            + " WHEN left(btrim(" + col + "), 1) IN ('{', '[') THEN (" + col + ")::jsonb"
            + " ELSE to_jsonb(" + col + ") END)"
        )


def downgrade() -> None:
    for col in ("datos_anteriores", "datos_nuevos"):
        op.execute(
            f"ALTER TABLE auditoria ALTER COLUMN {col} TYPE TEXT USING {col}::text"
        )
